### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by DrewRidley** [lmk02/BlockParty#45]
**Describe the bug**
```
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.pauhull.utils.particle.ParticlePlayer
        at de.leonkoth.blockparty.arena.Arena.<init>(Arena.java:120) ~[?:?]
        at de.leonkoth.blockparty.arena.Arena.create(Arena.java:132) ~[?:?]
        at de.leonkoth.blockparty.command.BlockPartyCreateCommand.onCommand(BlockPartyCreateCommand.java:25) ~[?:?]
        at de.leonkoth.blockparty.command.BlockPartyCommand.onCommand(BlockPartyCommand.java:100) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-79]
        ... 21 more
```

Your utility class can't be instantiated!

**Comment by syldium** [comment]
You have removed a part of the exception. :confused:
The version available on Spigot is not compatible with 1.16 and 1.17, you can find a compatible version on my [fork](https://github.com/syldium/BlockParty/releases/tag/v2.0.4-ALPHA2).
